### ISSUE TITLE
Notify if the user is submitting a request without filling the text fields 

### ISSUE THREAD

**Issue by SJoshi7** [PawanAIT/TinyUrl#1]
- An alert should be added for whenever an user tries to submit the request without filling the text fields (url to be shortened or the custom value).

- val of both the ids should be included in an condition and if either of it is empty then throw an alert stating that the user must fill the text fields.

**Comment by PawanAIT** [comment]
Custom field is not mandatory. if user provides Longurl and doesn't want anything special but random short url.
URL field is mandatory, just updated and fixed it.
I will make this project CI/CD. (continuous integration / continuous deployment)
whenever new commit is there in master it will be automatically deployed and we will be live with updated changes in few seconds.

**Comment by SJoshi7** [comment]
Yes sir, realized that the custom field need not be a compulsory field. Thank you for looking into the issue :)
